identidock:
 build: .
 ports:
  - "5000:5000"
 environment:
  ENV: DEV
 volumes:
  - ./app:/app
 links:
  - dnmonster
  - idredis
  
dnmonster:
 image: amouat/dnmonster:1.0
 
idredis:
 image: redis:3.0
 